// Generated from iBestSpeech Shared/LanguageDetector.swift — do not edit by hand.
// Function words (most-frequent, content-free) per Latin-script language,
// plus words that appear in exactly one list and therefore settle the language.
package org.bestdroid.tts

object DetectorWords {
    val functionWords: Map<String, Set<String>> = mapOf(
        "en" to setOf("the", "and", "is", "are", "you", "of", "to", "in", "it", "that", "was", "for", "on", "with", "as", "at", "be", "this", "have", "from", "not", "but", "they", "we", "what", "there", "when", "no", "your", "our", "will", "can", "if", "my", "all", "has", "been", "would", "should", "could", "about", "than", "them", "these", "may", "its", "up", "out", "do", "so", "any", "how"),
        "de" to setOf("der", "die", "das", "und", "ist", "nicht", "ein", "eine", "mit", "sich", "auf", "für", "von", "dem", "den", "zu", "im", "auch", "als", "aber", "wenn", "wir", "sie", "noch", "nur", "werden", "wird", "kann", "muss", "sind", "war", "haben", "hat", "dieser", "diese", "dieses", "nach", "bei", "aus", "durch", "gegen"),
        "fr" to setOf("le", "la", "les", "des", "est", "et", "un", "une", "que", "qui", "dans", "pour", "pas", "vous", "avec", "sur", "ce", "il", "elle", "nous", "mais", "plus", "au", "aux", "je", "son", "sa", "ses", "sont", "cette", "cet", "ont", "fait", "peut", "tout", "sans", "sous", "entre", "aussi", "comme"),
        "es" to setOf("el", "los", "las", "de", "que", "y", "en", "un", "una", "es", "por", "con", "para", "no", "se", "su", "al", "del", "lo", "como", "más", "pero", "yo", "este", "esta", "estos", "estas", "son", "fue", "han", "puede", "todo", "sin", "sobre", "entre", "cuando", "porque", "tiene"),
        "it" to setOf("il", "le", "di", "che", "e", "un", "una", "per", "con", "non", "si", "del", "al", "sono", "questo", "come", "più", "ma", "io", "gli", "della", "anche", "questo", "questa", "sono", "stato", "hanno", "può", "tutto", "senza", "tra", "fra"),
        "nl" to setOf("de", "het", "een", "en", "van", "is", "dat", "op", "te", "voor", "met", "zijn", "niet", "aan", "er", "ook", "als", "maar", "wij", "ze", "nog", "naar", "wordt", "kan", "moet", "was", "heeft", "deze", "dit", "door", "over", "tussen", "zonder"),
        "pt" to setOf("o", "os", "as", "de", "que", "e", "do", "da", "em", "um", "uma", "é", "para", "com", "não", "se", "por", "como", "mais", "mas", "eu", "este", "são", "esta", "foi", "tem", "pode", "tudo", "sem", "sobre", "entre", "quando", "porque"),
        "pl" to setOf("i", "w", "na", "z", "do", "że", "się", "nie", "jest", "to", "o", "a", "jak", "po", "tak", "ale", "dla", "od", "czy", "ja", "ze", "oraz", "przez", "jest", "są", "był", "ma", "może", "wszystko", "bez", "nad", "pod", "między", "kiedy", "ponieważ"),
    )
    val exclusiveWords: Map<String, Set<String>> = mapOf(
        "de" to setOf("akku", "aktualisierung", "anmelden", "bearbeiten", "benachrichtigung", "datei", "dateien", "einstellungen", "entsperren", "erfolgreich", "erforderlich", "geladen", "gerät", "installiert", "kalender", "kamera", "ladung", "löschen", "möglich", "nachricht", "netzwerk", "notizen", "passwort", "schließen", "speicher", "suchen", "teilen", "verbunden", "verfügbar", "wetter", "zugriff", "öffnen"),
        "en" to setOf("airplane", "available", "battery", "bluetooth", "brightness", "calendar", "camera", "cancel", "charging", "complete", "completed", "connected", "connection", "content", "copy", "could", "delete", "disabled", "display", "download", "downloads", "edit", "enabled", "expired", "failed", "installed", "keyboard", "loading", "network", "notifications", "paste", "please", "privacy", "region", "removed", "request", "retry", "screen", "scroll", "search", "security", "settings", "share", "should", "sign", "started", "stopped", "storage", "successfully", "swipe", "timed", "unable", "updates", "volume", "warning", "weather", "wifi", "would"),
        "es" to setOf("acceso", "ajustes", "almacenamiento", "archivo", "archivos", "batería", "bloqueo", "buscar", "carga", "cerrar", "compartir", "conexión", "contraseña", "correctamente", "cuenta", "cámara", "imposible", "iniciar", "mensaje", "necesario", "notificación", "red", "sesión"),
        "fr" to setOf("accès", "appareil", "batterie", "calendrier", "charge", "compte", "connecter", "connecté", "connexion", "déverrouiller", "fermer", "fichier", "fichiers", "impossible", "installé", "message", "modifier", "météo", "notes", "notification", "nécessaire", "ouvrir", "paramètres", "partager", "photos", "rechercher", "réseau", "réussi", "stockage", "supprimer", "verrouillage"),
        "it" to setOf("accedi", "accesso", "apri", "archiviazione", "batteria", "blocco", "carica", "cerca", "chiudi", "condividi", "connessione", "connesso", "correttamente", "disponibile", "elimina", "file", "foto", "fotocamera", "impossibile", "impostazioni", "installato", "messaggio", "meteo", "modifica", "necessario", "note", "notifica", "rete", "sblocca"),
        "nl" to setOf("aanmelden", "agenda", "apparaat", "batterij", "bericht", "beschikbaar", "bestand", "bestanden", "bewerken", "delen", "geslaagd", "geïnstalleerd", "instellingen", "melding", "netwerk", "nodig", "notities", "onmogelijk", "ontgrendelen", "openen", "opladen", "opslag", "sluiten", "toegang", "verbinding", "verbonden", "vergrendeling", "verwijderen", "wachtwoord", "weer", "zoeken"),
        "pl" to setOf("aparat", "blokada", "dostęp", "dostępny", "edytuj", "hasło", "kalendarz", "niemożliwe", "notatki", "odblokuj", "otwórz", "pamięć", "plik", "pliki", "pogoda", "powiadomienie", "połączenie", "połączony", "sieć", "szukaj", "udostępnij", "urządzenie", "ustawienia", "usuń", "wiadomość", "wymagane", "zainstalowano", "zaloguj", "zamknij", "zdjęcia", "ładowanie"),
        "pt" to setOf("acesso", "armazenamento", "arquivo", "arquivos", "bloqueio", "calendário", "carregando", "compartilhar", "conexão", "conta", "câmera", "definições", "disponível", "entrar", "fechar", "impossível", "mensagem", "necessário", "notificação", "palavra", "pesquisar", "rede"),
    )
}
