// Generated from iBestSpeech tools/dictionary.txt via Pronunciations.swift — do not edit by hand.
// Case-sensitive, whole-word matching: keeps e.g. AI from rewriting letters inside a French word.
package org.bestdroid.tts

object Pronunciations {
    // Longest first, so "iPadOS" matches before "iPad".
    val ordered: List<Pair<String, String>> = listOf(
        "FilenameExtension" to "file name extension",
        "Cryptocurrency" to "crypto currency",
        "FaceTimeAudio" to "Face Time Audio",
        "PlayStation" to "Play Station",
        "BluetoothLE" to "Bluetooth L E",
        "Touchscreen" to "touch screen",
        "PostgreSQL" to "post gres cue ell",
        "JavaScript" to "java script",
        "TypeScript" to "type script",
        "BitTorrent" to "bit torrent",
        "Ransomware" to "ran som ware",
        "Blockchain" to "block chain",
        "bottleneck" to "bottle neck",
        "Bottleneck" to "bottle neck",
        "Smartphone" to "smart phone",
        "Smartwatch" to "smart watch",
        "Screenshot" to "screen shot",
        "AppleCare" to "Apple Care",
        "Instagram" to "Insta gram",
        "Wikipedia" to "Wiki pedia",
        "Bluetooth" to "blue tooth",
        "WebSocket" to "web socket",
        "RetroBunn" to "Retro Bunn",
        "retrobunn" to "Retro Bunn",
        "Ecommerce" to "e commerce",
        "ecommerce" to "e commerce",
        "ApplePay" to "Apple Pay",
        "Facebook" to "Face Book",
        "LinkedIn" to "Linked Inn",
        "Snapchat" to "Snap Chat",
        "WhatsApp" to "Whats App",
        "FaceTime" to "Face Time",
        "iMessage" to "eye message",
        "AirPrint" to "air print",
        "Ethernet" to "ee ther net",
        "Firmware" to "firm ware",
        "Username" to "user name",
        "Filename" to "file name",
        "Hostname" to "host name",
        "PizzaCat" to "pizza cat",
        "Homepage" to "home page",
        "Firewall" to "fire wall",
        "Discord" to "Dis cord",
        "HomePod" to "Home Pod",
        "MacBook" to "Mac Book",
        "Netflix" to "Net flix",
        "Spotify" to "Spot ify",
        "YouTube" to "You Tube",
        "watchOS" to "watch oh ess",
        "AirDrop" to "air drop",
        "AirPods" to "air pods",
        "AirPlay" to "air play",
        "TouchID" to "touch eye dee",
        "AirPort" to "air port",
        "Unicode" to "you ni code",
        "Malware" to "mal ware",
        "Captcha" to "cap cha",
        "Wi-Fi's" to "why fye's",
        "Podcast" to "pod cast",
        "Webinar" to "web i nar",
        "Bitcoin" to "bit coin",
        "Offline" to "off line",
        "Website" to "web site",
        "Webpage" to "web page",
        "approx." to "approximately",
        "Reddit" to "red it",
        "TikTok" to "Tik Tok",
        "iPhone" to "eye phone",
        "iCloud" to "eye cloud",
        "iTunes" to "eye tunes",
        "iMovie" to "eye movie",
        "iPhoto" to "eye photo",
        "iPadOS" to "eye pad oh ess",
        "AirTag" to "air tag",
        "FaceID" to "face eye dee",
        "Ubuntu" to "oo boon too",
        "Debian" to "Deb ee an",
        "SQLite" to "ess cue lite",
        "Python" to "pie thon",
        "GitHub" to "git hub",
        "GitLab" to "git lab",
        "Logout" to "Log out",
        "Stange" to "stanggy",
        "stange" to "stanggy",
        "Online" to "on line",
        "macOS" to "mac oh ess",
        "Xcode" to "ex code",
        "Wi-Fi" to "why fye",
        "API's" to "A P I's",
        "MySQL" to "my ess cue ell",
        "y'all" to "yawl",
        "Y'all" to "yawl",
        "Emoji" to "eh moe jee",
        "emoji" to "eh moe jee",
        "ASCII" to "ass key",
        "UTF-8" to "U T F eight",
        "Devin" to "Devven",
        "devin" to "Devven",
        "Ebook" to "e book",
        "eBook" to "e book",
        "ebook" to "e book",
        "Email" to "e mail",
        "email" to "e mail",
        "dept." to "department",
        "govt." to "government",
        "iPad" to "eye pad",
        "iPod" to "eye pod",
        "iMac" to "eye mac",
        "tvOS" to "tee vee oh ess",
        "WiFi" to "why fye",
        "IPv4" to "eye pee vee four",
        "IPv6" to "eye pee vee six",
        "TIFF" to "T I F F",
        "MIDI" to "M I D I",
        "HDMI" to "H D M I",
        "eSIM" to "ee sim",
        "SSID" to "S S I D",
        "LLMs" to "L L M z",
        "BIOS" to "B I O S",
        "OSHA" to "oh shah",
        "etc." to "et cetera",
        "i.e." to "that is",
        "e.g." to "for example",
        "iOS" to "eye oh ess",
        "URI" to "U R I",
        "API" to "A P I",
        "GIF" to "G I F",
        "MP3" to "em pee three",
        "MP4" to "em pee four",
        "ZIP" to "Z I P",
        "ISO" to "I S O",
        "SIM" to "S I M",
        "SoC" to "ess oh see",
        "LLM" to "L L M",
        "CLI" to "C L I",
        "IDE" to "I D E",
        "GUI" to "G U I",
        "IoT" to "eye oh tee",
        "vs." to "versus",
        "IP" to "I P",
        "5G" to "five gee",
        "4G" to "four gee",
        "AI" to "A I",
        "ai" to "a i",
    )
}
